name: Deploy Home Page

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    uses: hacksawrazor/ci-cd/.github/workflows/deploy-react.yml@main
    with:
      node-version: '24'
      build-command: 'npm run build'
      build-dir: 'dist'
      deploy-path: '/var/www/html/hacksaw/home'
    secrets:
      SSH_HOST: ${{ secrets.SERVER_HOST_OCI }}
      SSH_USER: ${{ secrets.SERVER_USER_OCI }}
      SSH_KEY: ${{ secrets.SERVER_SSH_KEY_OCI }}
